### ISSUE TITLE
APIC Implementation and Interrupts

### ISSUE THREAD

**Issue by FallenDeity** [xuanplus/rust-os-dev#1]
So i was going through your code base and saw that you implemented the timer interrupt, In this case once interrupts are enabled and timer interrupt is registered it seems to work as expected.

![image](https://github.com/xuanplus/rust-os-dev/assets/61227305/50c1f658-539f-4b10-a956-3d6679ab235c)

Do you have any idea on how to approach the keyboard interrupt handler here? Also any reason you're not using the `x2apic` crate?

**Comment by xuanplus** [comment]
I'm sorry, but I didn't know how to use it at the time. So I just use so many unsafe impl like [osdev - apic](https://wiki.osdev.org/APIC)

In fact, I'm trying to change it completely.

**Comment by xuanplus** [comment]
Hi, bro!

I was busy with my studies before, and now I'm on vacation.

I change to use x2apic, and add keyboard support with io-apic successfully.

By the way, I change the font.

Hope it helps！
